Replace deprecated ContainerAwareCommand with Command
sonata-project/SonataCoreBundle pull request #734
Opened 2020-03-31 13:25 UTC by jorrit

## Subject

In preparation for SF 5.0 support the usage of ContainerAwareCommand must be removed.

For SonataListFormMappingCommand I've replaced it with a constructor that receives the container. I know this is not the way to use dependency injection, but in this case I think this is justified because it is simplest and the command is not usable in practice.

I am targeting this branch, because is is backwards compatible.

Closes #731

## Changelog

```markdown
### Fixed
- Replaced use of deprecated ContainerAwareCommand with Command.

### Security
```

2020-03-31 18:24 UTC, core23 requested changes

2020-03-31 18:24 UTC, core23 commented on src/CoreBundle/Command/SonataDumpDoctrineMetaCommand.php
> +class SonataDumpDoctrineMetaCommand extends Command
Sorry, but we only provide bug fixes for this bundle.

2020-04-01 06:33 UTC, jorrit commented
@core23 I propose this change to help move #732 forward, which I created to help move https://github.com/sonata-project/SonataAdminBundle/pull/5936 forward.

2021-05-18 12:49 UTC, closed without merging

2021-05-18 12:50 UTC, jordisala1991 commented
Not needed